name: Build Executable

on:
  push:
    branches:
      - main  # or the branch you want to trigger the action

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --add-data "aionKeySpammer/move.png;." --add-data "aionKeySpammer/close.png;." --add-data "aionKeySpammer/on.png;." --add-data "aionKeySpammer/off.png;." --add-data "aionKeySpammer/chat_box_template.png;." aionKeySpammer/aionKeySpammer.py

    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: aionKeySpammer
        path: dist/aionKeySpammer.exe
